### PR TITLE
The bubble_sort project update

### PR DESCRIPTION
**Pull request by promise-J**
This is the bubble sort code. I hope it sorts all it should

### CODE REVIEW

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🛑 🔧 
### Hi there Team ✋🏽 
Nicely done! Your bubble sort methods are all working as expected. But this was only possible after I removed the test cases you had in your methods.
- Please kindly remove them and leave just your methods in your file. Especially as your test example for bubble_sort_by had a syntax error. You omitted a closing parenthesis.
- Please also make sure all linters are passing
- Kindly update your Readme so it could look more professional

_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @promise-J and @danielufeli 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] There is syntax issue with `bubble_sort_by` by running `ruby bubblesort.rb`. Please fix the syntax issue.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by mke2111 — APPROVED** [review]
# **🎉 STATUS: APPROVED 🎉** 

## Hey @danielufeli   & @promise-J, 👋🏽 
 **Congratulations 🥳 🥂 . The methods work as expected. Keep up the great work.**

**You may now merge to the develop branch and submit a project completion form. 👍🏽** 

## Cheers!! 🍹 

## Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Comment by promise-J** [comment]
Thank you. we move.

**Pull request merged**
